### PR TITLE
[ER-971] Fix editor's height does not fit content on Android devices

### PR DESCRIPTION
**Pull request by khoaddtran**
When initializing the editor with an initial value, it might take time to sync the initial height through the Webview event. However, the sync only happened when the `value` changed that the synced height was not the latest height of the editor

https://user-images.githubusercontent.com/109196059/199192862-7bd50770-3b97-451a-a869-31ee25ae8a90.mov

## Changes proposed in this PR:
- User ResizeObserver to synced editor layout (height + width)

https://user-images.githubusercontent.com/109196059/199193039-b1c5f03c-2c07-4e3b-9df0-3008423d5d6c.mov

- Cursor position enhancement: when `autoFocus` is enabled, move the cursor to the very end of content on focus

### CODE REVIEW

**Comment by toan2406** [comment]
@khoaddtran Could you include a video to demo the issue?

**Review by khacluan — APPROVED** [review]

**Review by qhuyduong — APPROVED** [review]

**Comment by khoaddtran** [comment]
> @khoaddtran Could you include a video to demo the issue?

I updated with videos before and after the fix. Please help me review it @toan2406

**Review by toan2406 — APPROVED** [review]
Could you help check if this happens in the hero-design/rn playground too? I ask because it didn't happen before so not sure because of this lib or RN side

**Comment by khoaddtran** [comment]
> Could you help check if this happens in the hero-design/rn playground too? I ask because it didn't happen before so not sure because of this lib or RN side

It does not happen in the playground. However, it always happens to all the components that use the RichTextEditor component **with the initial value** (both from rn-hero-design and the new HD) in our mobile app.
I think the issue come from the difference between platform when handling the Webview, this PR will help us prevent it

**Comment by toan2406** [comment]
Thanks for confirming @khoaddtran 👍

**Pull request merged**
